In [1]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import nltk
from nltk.stem.porter import PorterStemmer
import re
import string
from nltk.corpus import stopwords


DF = pd.read_csv('FilteredTweets-sedentary.csv')
# get only the labelled tweets, in last 2 columns
DF = DF[DF['Sit == True  (1), else (0)'].notnull() & DF['Relevant == True (1), else (0)'].notnull()]

DF

,text,hashtags,placename,"Sit == True (1), else (0)","Relevant == True (1), else (0)"
0,b'@TELUSsupport Coming up on 2 hours waiting f...,NaN,"Comox Valley A, British Columbia",0.0,0.0
1,"b'@KevinSpacey Dude, I love you and your work....",NaN,"Edmonton, Alberta",0.0,0.0
2,b'Lizquen magpatulog kayo may work pa ako buka...,LizQuenOMNSeattle,"Richmond Hill, Ontario",0.0,0.0
3,b'BALLGAME #ASTROS!!! It will go down as one o...,"ASTROS,WorldSeries,Dodgers","Toronto, Ontario",0.0,0.0
4,"b""Limey rednecks can't stop swearin' outside t...",NaN,"Banff, Alberta",0.0,0.0
5,b'Spent the morning hanging out with SP then w...,NaN,"Calgary, Alberta",0.0,0.0
6,"b'@wintargetgame Yeah, trading that far up is ...",NaN,"Toronto, Ontario",0.0,0.0
7,"b""That's gotta be the most exciting baseball g...",worldseries,"Toronto, Ontario",1.0,1.0
8,b'https://t.co/ycUm5hVD04 Netflix and chill???...,NaN,"Spruce Grove, Alberta",1.0,1.0
9,"b'The best of games, the worst o games finally...",WorldSeries,"Vancouver, British Columbia",0.0,0.0
10,"b""My anniversary with Drunk Angie is on a Wedn...",NaN,"New Westminster, British Columbia",0.0,0.0
11,"b""The #WorldSeries2017 was exciting. But I've ...",WorldSeries2017,"Winnipeg, Manitoba",1.0,1.0
12,b'@jimmyfallon keep up the great work!\\nIll b...,NaN,"Ottawa, Ontario",0.0,0.0
13,b'The #WomensConvention was a whirlwind in the...,WomensConvention,"Hamilton, Ontario",0.0,0.0
14,b'Trying to decide between watching #Whitecaps...,"Whitecaps,WorldSeries,sportsnight","Coquitlam, British Columbia",1.0,1.0
15,"b'I hear so many, shit u not, so many say that...",NaN,"Toronto, Ontario",0.0,0.0
16,b'Maybe they should set the ball on fire to ma...,VANvSEA,"Milton, Ontario",1.0,1.0
17,b'Deeks to Kensi seeing Callen go by with a ki...,NCISLA,"Kitchener, Ontario",0.0,0.0
18,b'Has a defending Stanley Cup champion ever lo...,NaN,"Ottawa, Ontario",0.0,0.0
19,b'@Harvard @UniofOxford @Yale @UHouston @mcgil...,ClimateChange,"Montr̩al, Qu̩bec",0.0,0.0
20,b'We are very proud of this group of Life Chan...,NaN,"Yellowknife, Northwest Territories",0.0,0.0
21,b'@markthamonk I felt vicarious pain watching ...,NaN,"Halifax, Nova Scotia",1.0,0.0
22,"b'Every time I\\u2019m at a community event, h...",NaN,"Ottawa, Ontario",0.0,0.0
26,"b'Nice work, Barnesy!!!!'",NaN,"Calgary, Alberta",0.0,0.0
27,b'@cathmckenna Keep up great work minister. Do...,NaN,"Frenchman's Cove, Newfoundland and Labrador",0.0,0.0
28,b'@jenrauls @Kris_Sacrebleu @thismamatweets Ye...,NaN,"Quispamsis, New Brunswick",0.0,0.0
29,"b""Being spotted by a tennis #friend I haven't ...",friend,"Vancouver, British Columbia",0.0,0.0
30,"b'Kitchener tops Guelph 4-1, Logan Stanley wit...","GoJetsGo,OHL","Montr̩al, Qu̩bec",0.0,0.0
31,b'I sometimes feel like the only person left w...,NaN,"Kitchener, Ontario",0.0,0.0
32,b'Nicely toasted. Feeling like a big old pat o...,NaN,"Winnipeg, Manitoba",1.0,1.0
...,...,...,...,...,...
178,b'Well done Brian. Always working hard for the...,NaN,"Edmonton, Alberta",0.0,1.0
179,"b""@slipstream23575 Don't jump the gun. Is life...",NaN,"Calgary, Alberta",0.0,0.0
180,b'Put your free time during the strike to work...,NaN,"Barrie, Ontario",0.0,0.0
181,"b'""If you\'re like me, then you\'ve just watch...",NaN,"Vaughan, Ontario",1.0,1.0
182,b'@torontofc hey TFC why dont you start runnin...,NaN,"Brantford, Ontario",0.0,0.0
183,"b""I've got a nice little week off since work f...",NaN,"Sarnia, Ontario",0.0,1.0
184,"b""@ZombiApocolypse Thanks for giving it a try!...",NaN,"Ottawa, Ontario",0.0,0.0
185,"b""Sometimes, great ideas don't work out \\nand...",NaN,"East Hants, Nova Scotia",0.0,0.0
186,b'@CharleyReber I have not posted anything sin...,NaN,"Toronto, Ontario",0.0,0.0
187,"b""There we go! #Oilers score on the power-play...",Oilers,"Saskatoon, Saskatchewan",0.0,0.0
188,b'@VancouverBlade interested in partnering w n...,NaN,"Surrey, British Columbia",0.0,0.0
189,b'What are you working on to grow your communi...,TheTimeIsNow,"Cornwall, Prince Edward Island",0.0,0.0
190,b'@TacxSupport none of the keyboard controls w...,NaN,"London, Ontario",0.0,0.0
191,b'Sandra Spencer @alwayspivoting and the 5 pit...,3DSMacEwan,"Edmonton, Alberta",1.0,1.0
192,"b""You haven't replied to me since 3pm. You fir...",NaN,"Toronto, Ontario",0.0,0.0
193,b'I was born and now I\\u2019m still working o...,NaN,"Toronto, Ontario",1.0,1.0
194,b'#Preds 2016 6th RD pick Emil Pettersson has ...,"Preds,AHL","Montr̩al, Qu̩bec",0.0,0.0
195,b'@cathmckenna Keep up the good work and stand...,NaN,"Burnaby, British Columbia",0.0,0.0
196,"b'Want to work in #Kingston, Ontario? View our...","Kingston,Nursing,Job,Jobs,Hiring","Kingston, Ontario",0.0,0.0
197,"b""Today we're taking 800 of our friends @EF th...",EmpathyToy,"Toronto, Ontario",0.0,0.0
198,"b'Want to work in #Edmonton, AB? View our late...","Edmonton,Accounting,Job,Jobs,Hiring,CareerArc","Edmonton, Alberta",0.0,0.0
199,b'Watch out kids there\\u2019s a pumpkin watch...,NaN,"Toronto, Ontario",0.0,0.0
200,"b""Wouldn't you like to see your athlete, coach...",NaN,"Vancouver, British Columbia",0.0,0.0
201,b'Good luck and a great time to all our friend...,BC17,"Toronto, Ontario",1.0,1.0
202,"b'Want to work in #Waterloo, ON? View our late...","Waterloo,CustomerService,Job,Jobs,Hiring,Caree...","Waterloo, Ontario",0.0,0.0
203,b'I just wanna be cuddled up with my baby but ...,NaN,"Toronto, Ontario",1.0,1.0
204,b'My favourite @MetroVancouver work reports ba...,NaN,"Burnaby, British Columbia",0.0,0.0
205,b'@ThatFishCreigh @rymkrs Yeah missed last thr...,NaN,"Ottawa, Ontario",0.0,0.0
206,"b""i hate that when I react with anger people t...",NaN,"Hamilton, Ontario",0.0,0.0
207,"b""If you're looking for work in #Toronto, ON, ...","Toronto,job,Analytics,IT,Hiring","Toronto, Ontario",0.0,0.0

In [26]:
#Find common terms for each subset
def commonTerms(tweets): #df.text.tolist() here

	porter = nltk.PorterStemmer()
	all_tokens = []


	for i, value in enumerate(tweets):
	    
	    lowered = value.lower()
	    
	    tokens = nltk.word_tokenize(lowered)

	    # filter
	    tokens = [item for item in tokens if re.search(r'^[A-Za-z]+$', item)]

	    tokens = [item for item in tokens if item not in stopwords.words('english')]

	    stemmed_tokens = [porter.stem(item) for item in tokens]

	    all_tokens = all_tokens + stemmed_tokens



	freq = nltk.FreqDist(all_tokens)


	freq_terms = pd.DataFrame(freq.most_common(), columns =['words', 'frequency'])

	return freq_terms

In [27]:
# stratify the sample

relevant = DF[DF['Relevant == True (1), else (0)'] == 1.0]
not_relevant = DF[DF['Relevant == True (1), else (0)'] == 0.0]

sit = DF[DF['Sit == True  (1), else (0)'] == 1.0]
not_sit = DF[DF['Sit == True  (1), else (0)'] == 0.0]

In [28]:
commonTerms(relevant.text.tolist())

             words  frequency
0            watch         27
1             http         18
2                b         14
3             work         10
4             game          7
5             time          5
6              day          4
7            night          4
8             like          3
9            excit          3
10             man          3
11            hour          3
12             say          3
13            need          3
14       worldseri          3
15            play          3
16              na          3
17            make          3
18           still          2
19            show          2
20           littl          2
21              lt          2
22             end          2
23           leagu          2
24           video          2
25             got          2
26            ever          2
27            wait          2
28             cop          2
29         convers          2
..             ...        ...
205       xboxonex          1
206          write          1
207           till          1
208           satc          1
209          trash          1
210            liz          1
211           nice          1
212           week          1
213           ball          1
214         monday          1
215           rash          1
216           stop          1
217         forgot          1
218     soundtrack          1
219             fb          1
220           said          1
221     xboxcanada          1
222         hamont          1
223         friend          1
224        weekend          1
225          stack          1
226           amaz          1
227         butter          1
228        favorit          1
229        spencer          1
230           caus          1
231         person          1
232  sharedmaclean          1
233          allow          1
234           fact          1

[235 rows x 2 columns]

In [29]:
commonTerms(not_relevant.text.tolist())

          words  frequency
0          work        106
1          http         96
2             b         76
3           job         55
4          hire         32
5         watch         22
6     careerarc         21
7          game         18
8          open         16
9        latest         15
10         view         15
11         look         14
12          amp         12
13         want         11
14        check         11
15           go         10
16         good          9
17         time          8
18        click          7
19        peopl          7
20         goal          7
21          day          7
22      toronto          7
23          see          7
24         back          7
25       detail          7
26        great          6
27         live          6
28         year          6
29        think          6
..          ...        ...
753        sale          1
754      novemb          1
755     travers          1
756        chat          1
757        face          1
758         pit          1
759         nac          1
760     contest          1
761       idiot          1
762       actor          1
763      orient          1
764      afford          1
765        book          1
766       futur          1
767    shelburn          1
768          ns          1
769      cleric          1
770    musician          1
771        felt          1
772      insect          1
773         gon          1
774   construct          1
775     kieffer          1
776     cdnpoli          1
777        peac          1
778        pool          1
779      deserv          1
780      studio          1
781         hmm          1
782  magpatulog          1

[783 rows x 2 columns]

In [30]:
# top 20 terms in relevant but not in not_relevant

[x for x in commonTerms(relevant.text.tolist()).words[0:20] if x not in commonTerms(not_relevant.text.tolist()).words[0:20]]

[u'watch',
 u'http',
 'b',
 'work',
 'game',
 'time',
 'day',
 'night',
 'like',
 u'excit',
 'man',
 u'hour',
 'say',
 'need',
 u'worldseri',
 'play',
 'na',
 'make',
 'still',
 'show']

In [31]:
commonTerms(sit.text.tolist())

             words  frequency
0            watch         27
1             http         16
2                b         13
3             work          8
4             game          7
5            night          4
6             time          4
7              day          3
8             like          3
9            excit          3
10             man          3
11            hour          3
12             say          3
13            need          3
14       worldseri          3
15              na          3
16            make          3
17           still          2
18            show          2
19              lt          2
20             end          2
21           leagu          2
22           video          2
23            ever          2
24            wait          2
25             cop          2
26            last          2
27         convers          2
28            feel          2
29         respect          2
..             ...        ...
189          write          1
190           till          1
191           satc          1
192          trash          1
193            liz          1
194           ball          1
195           pain          1
196         monday          1
197           rash          1
198            whl          1
199           stop          1
200           felt          1
201     soundtrack          1
202             fb          1
203           said          1
204     xboxcanada          1
205         hamont          1
206         friend          1
207        kieffer          1
208        weekend          1
209          stack          1
210           amaz          1
211         butter          1
212        favorit          1
213        spencer          1
214           caus          1
215         person          1
216  sharedmaclean          1
217          allow          1
218           fact          1

[219 rows x 2 columns]

In [32]:
commonTerms(not_sit.text.tolist())

          words  frequency
0          work        108
1          http         98
2             b         77
3           job         55
4          hire         32
5         watch         22
6     careerarc         21
7          game         18
8          open         16
9        latest         15
10         view         15
11         look         14
12          amp         12
13         want         11
14        check         11
15           go         10
16         good          9
17         time          9
18        peopl          8
19          day          8
20        click          7
21      toronto          7
22          see          7
23         back          7
24       detail          7
25        great          6
26         live          6
27         year          6
28        think          6
29          get          6
..          ...        ...
763      novemb          1
764     travers          1
765        chat          1
766        face          1
767         pit          1
768         nac          1
769     contest          1
770       idiot          1
771       actor          1
772      orient          1
773      afford          1
774        book          1
775       futur          1
776    shelburn          1
777          ns          1
778        nice          1
779      cleric          1
780    musician          1
781       teeth          1
782      forgot          1
783      insect          1
784         gon          1
785   construct          1
786     cdnpoli          1
787        peac          1
788        pool          1
789      deserv          1
790      studio          1
791         hmm          1
792  magpatulog          1

[793 rows x 2 columns]

In [33]:
# top 20 terms in relevant but not in not_relevant

[x for x in commonTerms(sit.text.tolist()).words[0:20] if x not in commonTerms(not_sit.text.tolist()).words[0:20]]

[u'watch',
 u'http',
 'b',
 'work',
 'game',
 'night',
 'time',
 u'day',
 'like',
 u'excit',
 'man',
 u'hour',
 'say',
 'need',
 u'worldseri',
 'na',
 'make',
 'still',
 'show',
 'lt']